const PRICE=9.90, BTS=89.90, THRESHOLD=100, LOCAL=['PALHOCA','FLORIANOPOLIS'];
let mode=localStorage.getItem('orderMode')||'regular', qty=Number(localStorage.getItem('orderQty')||1), discount=localStorage.getItem('btsDiscount')==='1';
let freight=Number(localStorage.getItem('shippingPrice')||0), freightFree=localStorage.getItem('shippingFree')==='1';
const $=id=>document.getElementById(id), brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function normalize(s){return String(s||'').toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function productTotal(){return mode==='bts'?Math.max(0,BTS-(discount?BTS*.1:0)):PRICE*qty}
async function renderPhotos(){const files=await PhotoStore.load(); $('photoCount').textContent=files.length; $('photoGrid').innerHTML=files.map((f,i)=>`<div class="photo-card"><img src="${f.dataUrl}" alt="Foto ${i+1}"><button data-i="${i}" aria-label="Remover">×</button><small>${f.name}</small></div>`).join(''); $('photoStatus').textContent=files.length?`${files.length} foto(s) selecionada(s).`:'Nenhuma foto enviada ainda.';document.querySelectorAll('.photo-card button').forEach(b=>b.onclick=async()=>{const all=await PhotoStore.load();all.splice(Number(b.dataset.i),1);await PhotoStore.save(all);renderPhotos()})}
function update(){ $('productLabel').textContent=mode==='bts'?'Kit BTS • 7 bolas':'Bolas personalizadas'; $('qtyLabel').textContent=mode==='bts'?7:qty; $('freightLabel').textContent=freightFree?'GRÁTIS':(freight?brl(freight):'A calcular'); $('totalLabel').textContent=brl(productTotal()+(freight||0)); const u=JSON.parse(localStorage.getItem('esferasUser')||'null'); $('authNotice').innerHTML=u?`Você está conectado como <b>${u.name}</b>. <span class="address-chip">${u.email}</span>`:'Você pode continuar sem conta, mas uma conta ajuda a acompanhar seus pedidos.'; if(u){$('customerEmail').value=u.email||'';$('customerName').value=u.name||'';$('customerCpf').value=u.cpf||'';}}
function fmtCep(v){const n=String(v||'').replace(/\D/g,'').slice(0,8);return n.length>5?n.slice(0,5)+'-'+n.slice(5):n}
$('cepCheckout').addEventListener('input',e=>e.target.value=fmtCep(e.target.value));
async function fetchFreight(){const cep=$('cepCheckout').value.replace(/\D/g,''); if(cep.length!==8){$('freightMsg').textContent='Digite um CEP válido.';return;} try{const via=await fetch(`https://viacep.com.br/ws/${cep}/json/`).then(r=>r.json());if(via.erro)throw 0; $('addressCity').value=via.localidade;$('addressState').value=via.uf;$('addressStreet').value=via.logradouro||''; const city=normalize(via.localidade); if(productTotal()>THRESHOLD && LOCAL.includes(city)){freight=0;freightFree=true;localStorage.setItem('shippingFree','1');localStorage.setItem('shippingPrice','0');$('freightMsg').innerHTML='<span class="success">Frete grátis para Palhoça/Florianópolis em compras acima de R$ 100.</span>';update();return;} freightFree=false; localStorage.setItem('shippingFree','0'); $('freightMsg').innerHTML='<span>CEP localizado. A cotação nacional será calculada pela integração de frete no checkout.</span>'; update();}catch{ $('freightMsg').textContent='Não foi possível localizar este CEP.'}}
$('cepCheckout').addEventListener('blur',fetchFreight);
$('photoInput').addEventListener('change',e=>addFiles(e.target.files)); const dz=$('dropzone'); ['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addFiles(e.dataTransfer.files));
async function addFiles(list){const current=await PhotoStore.load(); for(const file of Array.from(list)){if(!['image/jpeg','image/png','image/webp'].includes(file.type)){continue}if(file.size>8*1024*1024){continue} if(current.length>=3) break; const dataUrl=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});current.push({name:file.name,type:file.type,size:file.size,dataUrl});} await PhotoStore.save(current);renderPhotos();}
$('goPayment').onclick=async()=>{const files=await PhotoStore.load();if(mode==='regular'&&!files.length){if(!confirm('Você ainda não enviou uma foto. Deseja continuar mesmo assim?'))return;} const u=JSON.parse(localStorage.getItem('esferasUser')||'null'); localStorage.setItem('customerDraft',JSON.stringify({email:$('customerEmail').value,name:$('customerName').value,cpf:$('customerCpf').value,cep:$('cepCheckout').value,number:$('addressNumber').value,street:$('addressStreet').value,city:$('addressCity').value,state:$('addressState').value})); localStorage.setItem('orderTotal',String(productTotal()+freight)); window.location.href='pagamento.html';};
$('cepCheckout').value=localStorage.getItem('customerCep')||''; renderPhotos(); update();